modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/MapperTV/roadstuff/issues"
[[mods]]
modId="roadstuff"
version="${file.jarVersion}"
displayName="Road Stuff"
#updateJSONURL="http://myurl.me/"
displayURL="http://mapper.tv/roadstuff/"
logoFile="roadstuff_logo.png"
credits="The Forge team and community for the help and resources."
authors="Mapper"
description='''Road Stuff 2 brings you everything you need to create the roads of your dreams!'''

[[dependencies.roadstuff]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.roadstuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.roadstuff]]
    modId="mapperbase"
    mandatory=true
    versionRange="[1.18.1-4.0,)"
    ordering="AFTER"
    side="BOTH"